import React from 'react';
import Head from 'next/head';

export default ({ title }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />

      <link
        rel='stylesheet'
        href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css'
      />
      <link
        href={`https://fonts.googleapis.com/css2?family=Raleway:wght@200;300;400;500;600;700;800;900&display=swap`}
        rel='stylesheet'
      />

      <link rel='stylesheet' href='/css/bootstrap.min.css' />
      <link rel='stylesheet' href='/css/style.css' />
      <link rel='stylesheet' href='/css/responsive.css' />
      <script src='/js/jquery.min.js'></script>
    </Head>
  );
};
